name: CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    react-app-workflow:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            # - name: npm ci
            #   run: npm ci
            # - name: test
            #   run: npm test
            - name: format
              run: npm run prettier
            - name: lint
              run: npm run lint
            - name: typescript
              run: npm run typescript
            - name: build
              run: npm run build --if-present
