name: CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    react-app-workflow:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            # - name: npm ci
            #   run: npm ci
            # - name: test
            #   run: npm test
            - name: lint
              run: yarn lint
            - name: typescript
              run: yarn typescript
            - name: build
              run: yarn build --if-present
